// Tests the distribution generated by Java's Math.random() function.

public class TestRandom {
	public static void main(String[] args) {
		int numTests = Integer.parseInt(args[0]); // The number of random number tests.

		int numUpperHalf = 0; // The number of random numbers over 0.5.
		int numLowerHalf = 0; // The number of random numbers under or equal to 0.5.

		// Counts the number of random numbers over and under 0.5.
		int n = 0;
		while (n < numTests) {
			double randomNum = Math.random();
			if (randomNum > 0.5) {
				numUpperHalf += 1;
			} else {
				numLowerHalf += 1;
			}
			n += 1;
		}
		
		// Prints the number of random numbers over and under or equal to 0.5.
		System.out.println("> 0.5:  " + numUpperHalf + " times");
		System.out.println("<= 0.5: " + numLowerHalf + " times");

		// Prints the ratio between the two halfs, unless the lower half is 0.
		if (numLowerHalf != 0) {
			double ratio = (double) numUpperHalf / numLowerHalf;
			System.out.println("Ratio:  " + ratio);
		}
	}
}