// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		// Gets the number of random number tests.
		int numTests = Integer.parseInt(args[0]);

		int numUpperHalf = 0; // the number of random numbers over 0.5.
		int numLowerHalf = 0; // the number of random numbers under or equal to 0.5.
	    int n = 0;
		double randomNum;

		// Counts the number of random numbers over and under 0.5.
		while (n < numTests) {
			randomNum = Math.random();
			if (randomNum > 0.5) {
				numUpperHalf += 1;
			} else {
				numLowerHalf += 1;
			}
			n += 1;
		}

		System.out.println("> 0.5: " + numUpperHalf);
		System.out.println("<= 0.5: " + numLowerHalf);

		if (numLowerHalf != 0) {
			double ratio = numUpperHalf / numLowerHalf;
			System.out.println("Ratio: " + ratio);
		}
	}
}
